const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../calendar-core.js'),fixtures=require('./fixtures/calendar.cjs');
test('35 lessons and grouped receipt preserve the multi-course fixture totals',()=>{const a=fixtures.planned(),rows=a.templates.map(t=>({name:`${t.subject}-개별(${t.teacher})-${t.hours}h`,hours:t.hours,rate:t.rate,dates:t.dates})),lessons=C.expand(rows,'select','2026-09');assert.equal(lessons.length,35);assert.equal(lessons.reduce((s,r)=>s+r.hours,0),113);assert.equal(lessons.reduce((s,r)=>s+r.amount,0),3262500);assert.equal(C.groups(lessons).length,5);});
test('same day subjects, teachers and additional sessions stay independent',()=>{const rows=[{name:'수학-개별(A)-3h',hours:3,rate:87500,dates:[10],schedule:{overrides:{10:{hours:2,rate:62500}},additional:[{id:'second',day:10,hours:1,rate:30000}]}},{name:'국어-개별(B)-3h',hours:3,rate:87500,dates:[10]}];const l=C.expand(rows,'select','2026-09');assert.equal(l.length,3);assert.equal(l.filter(r=>r.subject==='국어')[0].amount,87500);rows[0].schedule.removed=[10];assert.equal(C.expand(rows,'select','2026-09').length,2);assert.equal(C.expand(rows,'select','2026-09',[10]).length,0);});
test('round per lesson; decimal hourly rates; unknown is not explicit zero',()=>{const l=C.expand([{name:'수학',hours:3,rate:29166.6667,rateMode:'perHour',dates:[1,2,3]},{name:'영어',hours:2,rate:0,dates:[1]},{name:'국어',hours:2,rate:0,rateKnown:false,dates:[1]}],'select','2026-09');assert.equal(l.filter(r=>r.subject==='수학').reduce((s,r)=>s+r.amount,0),262500);assert.equal(l.find(r=>r.subject==='영어').amount,0);assert.equal(l.find(r=>r.subject==='국어').amount,null);});
test('patterns require confirmation and exclude cancellations, absence, makeup and one-off notes',()=>{const row=(id,date,kind='regular',note='')=>({id,date,className:'수학-개별정규(A)-3h',teacher:'A',start:'14:00',end:'17:00',minutes:180,amount:87500,kind,note});const result=C.candidates({studentId:'a',month:'2026-09',lessons:[row('a','2026-09-01'),row('b','2026-09-08'),row('c','2026-09-15','cancel'),row('d','2026-09-22','absence'),row('e','2026-09-29','regular','오늘만')]});assert.equal(result.rows.length,1);assert.equal(result.rows[0].sourceIds.length,2);assert.equal(result.excluded.length,3);assert.ok(result.rows[0].reasons.includes('다음 달 시간표·변경 안내 대조'));});
test('source picker groups a class across weekdays but preserves two independent same-day sessions',()=>{
    const row=(id,date,start,end)=>({id,date,className:'수학-개별정규(A)-3h',teacher:'A',start,end,minutes:180,amount:87500,kind:'regular'});
    const across=C.groupCandidates(C.candidates({month:'2026-09',lessons:[row('a','2026-09-01','14:00','17:00'),row('b','2026-09-08','15:00','18:00'),row('c','2026-09-03','14:00','17:00')]}).rows);
    assert.equal(across.length,1);assert.deepEqual(across[0].weekdays.map(day=>[day.day,day.count,day.suggested]),[[2,2,true],[4,1,false]]);
    const sameDay=C.groupCandidates(C.candidates({month:'2026-09',lessons:[row('a','2026-09-01','10:00','13:00'),row('b','2026-09-01','14:00','17:00')]}).rows);
    assert.equal(sameDay.length,2);assert.notEqual(sameDay[0].id,sameDay[1].id);
});
test('comparison preserves missing, zero, new and removed subjects',()=>{const r=C.compareHours({수학:20,영어:10,과학:0},{수학:25,영어:0,국어:10});assert.equal(r.find(x=>x.subject==='수학').percent,-20);assert.equal(r.find(x=>x.subject==='영어').label,'신규');assert.equal(r.find(x=>x.subject==='과학').label,'비교 자료 없음');assert.equal(r.find(x=>x.subject==='국어').percent,-100);});
test('schedule validation rejects invalid dates and markup before state changes',()=>{assert.throws(()=>C.validateSchedule({overrides:{32:{hours:2,rate:100}}},'2026-09'));assert.throws(()=>C.validateSchedule({overrides:{2:{hours:'<img>',rate:100}}},'2026-09'));assert.throws(()=>C.validateSchedule({additional:[{id:'bad',day:2,hours:2,rate:-1}]},'2026-09'));});

test('legacy aggregate rounding remains stable while new calculations round per lesson',()=>{const r={name:'수학',hours:1.25,rate:10000.5,rateMode:'perHour',dates:[1,2,3],legacyAggregate:true};assert.equal(C.expand([r],'select','2026-09').reduce((n,r)=>n+r.amount,0),37502);r.legacyAggregate=false;assert.equal(C.expand([r],'select','2026-09').reduce((n,r)=>n+r.amount,0),37503);});
