// Browser QA: synthetic students and data; no production requests or record writes.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),fixtures=require('./fixtures/calendar.cjs');
const root=path.resolve(__dirname,'..'),a=fixtures.planned(),b=fixtures.historical();
const A={version:8,currentTab:'select',studentId:'qa',studentName:'검증 학생 A',targetYear:2026,targetMonth:9,selectRows:a.templates.map(t=>({name:`${t.subject}-개별(${t.teacher})-${t.hours}h`,hours:t.hours,rate:t.rate,dates:t.dates,rateMode:'perClass'})),adjustmentItems:a.adjustments};
const B={version:7,currentTab:'history',studentId:'qb',studentName:'검증 학생 B',targetYear:2026,targetMonth:8,historyData:b.events.map(r=>({year:2026,month:8,day:r.day,subject:`${r.subject}-${r.type}(${r.teacher})-${r.sourceHours||r.hours}h`,teacher:r.teacher,attend:r.status,hours:r.hours,amount:r.amount,originalAmount:r.amount,hourlyRate:r.sourceHourly||0,startTime:r.start+':00',endTime:r.end+':00'})),adjustmentItems:b.adjustments};
const auth=`export async function initializeAuth(onState){
const A=${JSON.stringify(A)},B=${JSON.stringify(B)};window.qaSaved=null;window.qaFail=false;const toolbar=document.createElement('div');toolbar.id='qaToolbar';toolbar.style='padding:8px;background:#eff6ff';toolbar.innerHTML='<b>합성 QA · 실제 학생/서버 연결 없음</b> <button id="qaA">사례 A</button> <button id="qaB">사례 B</button> <button id="qaRestore">저장본 복원</button> <button id="qaError">조회 실패 전환</button> <output id="qaResult"></output>';document.body.prepend(toolbar);
document.getElementById('qaA').onclick=()=>{applyCalculatorState(A);serverRecordHistory=[{recordId:'a',studentName:A.studentName,payload:A,currentTab:A.currentTab,targetYear:2026,targetMonth:9,totalText:'2,900,000원',savedAt:'2026-09-30'},{recordId:'b',studentName:B.studentName,payload:B,currentTab:B.currentTab,targetYear:2026,targetMonth:8,totalText:'70,000원',savedAt:'2026-09-30'}];renderServerRecordList();};document.getElementById('qaB').onclick=()=>applyCalculatorState(B);document.getElementById('qaRestore').onclick=()=>{if(window.qaSaved)applyCalculatorState(window.qaSaved);};document.getElementById('qaError').onclick=()=>{window.qaFail=!window.qaFail;document.getElementById('qaResult').textContent=window.qaFail?'조회 실패 켜짐':'조회 실패 꺼짐';};
const gateway={rpc:async(name,p={})=>{if(window.qaFail)return{data:null,error:{message:'합성 조회 오류'}};if(name==='feecalc_students')return{data:[{id:'qa',name:A.studentName,school:'세화여고',grade:'1'},{id:'qb',name:B.studentName,school:'서울고',grade:'3'}]};if(name==='feecalc_progress'){const month=p.p_month;const ds=month==='2026-09'?[1,8,15,22,29]:[4,11,18,25];return{data:{studentId:p.p_student_id,month,fetchedAt:'2026-09-30T02:00:00Z',lessons:ds.map((day,i)=>({id:'source'+i,date:month+'-'+String(day).padStart(2,'0'),className:'수학-개별정규(강사 C)-3h',teacher:'강사 C',start:'14:00',end:'17:00',minutes:180,amount:87500,kind:i===3?'cancel':'regular',note:i===4?'오늘만':''}))}};}if(name==='feecalc_save_record'){window.qaSaved=structuredClone(p.p_payload);document.getElementById('qaResult').textContent='합성 저장 완료';return{data:{record_id:'qa-saved',student_name:p.p_student_name,payload:p.p_payload}};}return{data:[]};}};
queueMicrotask(()=>onState({state:'ready',actor:{uid:'qa-staff',name:'검증 직원'},user:{uid:'qa-staff'},gateway}));return{gateway};}
`;
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/auth-client.mjs'){res.setHeader('Content-Type','text/javascript');res.end(auth);return;}if(pathname==='/__qa_export'&&req.method==='POST'){const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>{fs.writeFileSync('/tmp/feecalc-calendar-output.png',Buffer.concat(chunks));res.end('ok');});return;}const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{res.setHeader('Content-Type',file.endsWith('.css')?'text/css':/\.(m?js)$/.test(file)?'text/javascript':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});server.listen(Number(process.env.PORT)||8766,'127.0.0.1',()=>console.log('Synthetic calendar QA at http://127.0.0.1:'+(process.env.PORT||8766)));
